### ISSUE TITLE
Comments in Main.js

### ISSUE THREAD

**Issue by MasterOfTheTiger** [UltraLang/UltraLangScript#2]
It would be helpful for contributors for the code to be thoroughly commented in.

**Comment by Narulacodes** [comment]
That Would Be Nice. @amazinigmech2418  Can i have owner acces?

**Comment by trafort** [comment]
Comments would help users understand. Love it

**Comment by kyleplo** [comment]
Good idea, I added it. @trafort, want to join?

**Comment by trafort** [comment]
Sure.
