### ISSUE TITLE
Add ObjectifyJS to UltraLangScript definitions to improve the functionality.

### ISSUE THREAD

**Issue by amazinigmech2418** [UltraLang/UltraLangScript#5]

**Comment by amazinigmech2418** [comment]
@kyleplo ObjectifyJS will allow more object-oriented functions.

**Comment by kyleplo** [comment]
Can you give me an example? I don't understand.

**Comment by kyleplo** [comment]
Okay, now I understand. When I searched Google for ObjectifyJS, [this came up](https://github.com/ty1824/ObjectifyJS). I now see what you mean. I think we can add it.

**Comment by kyleplo** [comment]
Created a PR. Merge if you like it.
